### ISSUE TITLE
Is the liri shell still maintained?

### ISSUE THREAD

**Issue by wat9rz** [qmlos/shell#217]
This beautiful desktop looks like it hasnt been maintained in ages. it is also very hard to build right

**Comment by plfiorini** [comment]
It is still maintained, but the development is happening at a slower pace.
Currently there are many changes under the hood in the compositor and shell department that are quiet big and not yet ready to be made public.  There is no ETA but at some point, these changes will be released.
Also, the plan is to focus more on the desktop rather than the distro in order to concentrate the resources in one key area.
